package user.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import user.db.User;
import user.db.User2;

import user.db.UserDao;
import user.db.User2Dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig user2DaoConfig;

    private final UserDao userDao;
    private final User2Dao user2Dao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        user2DaoConfig = daoConfigMap.get(User2Dao.class).clone();
        user2DaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        user2Dao = new User2Dao(user2DaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(User2.class, user2Dao);
    }
    
    public void clear() {
        userDaoConfig.getIdentityScope().clear();
        user2DaoConfig.getIdentityScope().clear();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public User2Dao getUser2Dao() {
        return user2Dao;
    }

}
